# Hyperparameters of Particle Transformer.

ParticleTransformer:

  ParEmbed: # (pt_rel, delta_eta, delta_phi)
    input_dim: 3 # 16
    embed_dim: [128, 512, 128]

  IntEmbed: # (delta, kt, z)
    input_dim: 3 # 4
    embed_dim: [64, 64, 64]

  ParAtteBlock:
    num_heads: 8
    fc_dim: 512
    dropout: 0.1

  ClassAtteBlock:
    num_heads: 8
    fc_dim: 512
    dropout: 0.0

  num_ParAtteBlock: 8
  num_ClassAtteBlock: 2

# Hyperparameters of Particle Net.

ParticleNet:

  input_dim: 3 # (pt_rel, delta_eta, delta_phi)

  edge_conv: [
      # [top_k_neighbor, [[channel_1_in, channel_1_out], [channel_2_in, channel_2_out], ...]]
      [3, [[64, 64], [64, 64], [64, 64]]], # 16
      [3, [[64, 128], [128, 128], [128, 128]]], # 16
  ]

  fc: [
      # [dropout_rate, [channel_in, channel_out]]
      [0.1, [128, 256]],
      [0.1, [256, 256]],
  ]

# Hyperparameters of Particle Flow Network.

ParticleFlowNetwork:
  Phi:
    in_channel: 3
    out_channel: 256
    hidden_channel: 100
    num_layers: 2
  F:
    in_channel: 256
    hidden_channel: 100
    num_layers: 2