# Configurations used in `main.ipynb` (or `main.py`)

Settings:
  mode: '111'         # Stands for ('train', 'valid', 'test').
  use_wandb: true     # Whether using wandb to monitor training procedure.
  print_log: true    # Whether print logs during training.
  suffix: ''          # Suffix description of this training.

Train:
  max_epochs: 30            # Maximum number of epochs.
  log_every_n_steps: 50     # Log every n steps.
  num_sanity_val_steps: 0   # To avoid calculating AUC for single class.
  ckpt_monitor: 'valid_auc' # Monitor AUC of validation data.
  ckpt_mode: 'max'          # Save the model with the maximum AUC.
  ckpt_top_k: 5             # Save top k models with highest AUC.

Data:
  num_train: 100000     # Number of training data per channel.
  num_valid: 10000      # Number of validation data per channel.
  num_test: 10000       # Number of testing data per channel.
  batch_size: 64       # Batch size.
  pt_threshold: 0.0    # Percentage of daughter pt to jet pt threshold.
  min_num_ptcs: 4      # Minimum number of particles per jet.
  max_num_ptcs: null   # Maximum number of particles per jet.
  
TopQCD:
  dataset: 'TopQCD'    # Dataset name.
  num_classes: 2       # Number of classes.
  pt_min: 550          # Minimum of jet pt.
  pt_max: 650          # Maximum of jet pt.

JetNet:
  dataset: 'JetNet'    # Dataset name.
  num_classes: 5       # Number of classes.
  pt_min: 800          # Minimum of jet pt.
  pt_max: 1200         # Maximum of jet pt.